---
repos:

- repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
  rev: 0.2.2
  hooks:
  - id: yamlfmt
    args: [--mapping, '2', --sequence, '2', --offset, '0', --colons, --width, '150']

- repo: https://github.com/charliermarsh/ruff-pre-commit.git
  rev: v0.0.261
  hooks:
  - id: ruff
    args: [--fix, --format, grouped]

- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
  - id: black

- repo: https://github.com/pocc/pre-commit-hooks
  rev: v1.3.5
  hooks:
  - id: clang-format
    args: [-i]

- repo: https://github.com/cmake-lint/cmake-lint
  rev: 1.4.2
  hooks:
  - id: cmakelint
    args: [--linelength=88]
    # for formatting shell files
    # - repo: https://github.com/syntaqx/git-hooks
    #   rev: v0.0.17
    #   hooks:
    #     - id: shfmt
- repo: https://github.com/detailyang/pre-commit-shell
  rev: v1.0.6
  hooks:
  - id: shell-lint
